### PR TITLE
[TASK] Ignore Me

### PR DESCRIPTION
**Pull request by susannemoog**

### CODE REVIEW

**Comment by marble** [comment]
Can I close this?

**Comment by susannemoog** [comment]
@marble please don't, opened it to demonstrate current github problems with workflows, see https://github.community/t5/GitHub-Actions/quot-if-github-ref-x-quot-while-not-on-the-branch-now-causes-a/td-p/53066 (and the checks here). I will close this once we get an answer / fix for that.

**Comment by marble** [comment]
I see. However this worked: https://github.com/TYPO3-Documentation/sphinx_typo3_theme/pull/71 
Seems like a bug in Github Actions?!

**Comment by susannemoog** [comment]
@marble yes, it was a bug in github actions - see the link I posted :-) it's fixed now.

**Pull request closed without merging**
