### PR TITLE
[BUGFIX] Do not override code styling within description list

### PR DESCRIPTION
**Pull request by nhovratov**
Only override the code styling of the description name (confval).

### CODE REVIEW

**Comment by marble** [comment]
Can you please say some words about what you want to achieve? Screenshots are welcome. Remove a ruleset for a native tag ("code") and replacing it by just a class seems a very heavy intervention.

**Comment by nhovratov** [comment]
Of course. You see this for example:
Screenshot 2021-07-12 at 15-36-27 addRecord — TCA Reference master documentation

Only the styling of `addRecord` with the class `descname` should be overriden by that selector.
Right now every code-tag has this styling inside the description list (type="group", table, edit popup, below, after).

**Comment by marble** [comment]
I will check this and then let you know. Thanks for contributing.

**Comment by marble** [comment]
Please give me the link to that 'addRecord' example.

**Comment by nhovratov** [comment]
https://docs.typo3.org/m/typo3/reference-tca/master/en-us/ColumnsConfig/CommonProperties/FieldControl/AddRecord.html

**Comment by marble** [comment]
I've updated my comment.

**Comment by nhovratov** [comment]
I think it's not intended to look like this. The styling of inline code looks usually like this:
Screenshot 2021-07-14 at 16-44-25 About the examples — TCA Reference master documentation

But with the introduction of these description lists, the styling was accidentely overridden.
It was probably only meant for the description title, which also has the code tag.

**Comment by marble** [comment]
Ah, now I see what you mean. Will have a second look.

**Comment by marble** [comment]
Good work, thank you very much. Tip: Create a separate branch in your repository for each pull request. The expected look now is:
grafik

**Comment by nhovratov** [comment]
Thank you very much for taking the time and for the tip!
This was bothering me for some time now :)
Great work on the documentation in general!

**Pull request merged**
