### PR TITLE
[FEATURE] Add a link to the TYPO3 Code of Conduct to the footer

### PR DESCRIPTION
**Pull request by oliverklee**
The TYPO3 Code of conduct should be easily accessible from all
official TYPO3-related sites so that people in distress due to
a possible incident do not need to invest much time trying to
find out how to get help.

### CODE REVIEW

**Comment by alexander-nitsche** [comment]
My two cents on it: 

(1) Although it is great to have the Code of Conduct i would rate it as low priority footer link compared to others, like Home, Repository, Contact, .. , Legal Terms and therefore wonder if it could become part of one of the pages that are already linked to reduce footer space. If not, then ->(2).

(2) Next when looking at the implementation i would not add it to the line of Repository, Issues, Home, Contact and Discussions, which are all very documentation/extension related, but to the last line which has already common TYPO3 links like Legal notice and Privacy policy. And i would not make it hard coded but also a variable that can be set explicitly (Martin is on it for privacy policy and legal terms already).

Greetings, Alex

**Comment by oliverklee** [comment]
@alexander-nitsche Hi! Thanks for your thoughts!

1) I find it important to have it on each and every page. People who have been assaulted or who have witnessed an incident might be distressed, and I would like to avoid them having to search through the TYPO3 pages, trying to guess under which other pages (contact? legal?) the CoC and the incident response might be found.

> but to the last line which has already common TYPO3 links like Legal notice and Privacy policy.

That's within `class="footer-meta-navigation"`, right?

> And i would not make it hard coded but also a variable that can be set explicitly (Martin is on it for privacy policy and legal terms already).

What would be the benefit of this approach?

**Comment by alexander-nitsche** [comment]
> And i would not make it hard coded but also a variable that can be set explicitly (Martin is on it for privacy policy and legal terms already).
> What would be the benefit of this approach?

This would allow us to remove the link for documentations that want to use the TYPO3 Sphinx template for rendering but do not want to link to the official TYPO3 terms & conditions & code of conduct. We would streamline the approach of setting all links explicitly - with the burden of having to set them explicitly.

**Comment by alexander-nitsche** [comment]
> but to the last line which has already common TYPO3 links like Legal notice and Privacy policy.
> That's within class="footer-meta-navigation", right?

Yes.

**Comment by oliverklee** [comment]
> This would allow us to remove the link for documentations that want to use the TYPO3 Sphinx template for rendering but do not want to link to the official TYPO3 terms & conditions & code of conduct. We would streamline the approach of setting all links explicitly - with the burden of having to set them explicitly.

Are there uses for the TYPO3 Sphinx template that is not part of the TYPO3 community (i.e., not within the scope of application of the TYPO3 CoC) which we need to cover?

**Comment by oliverklee** [comment]
> but to the last line which has already common TYPO3 links like Legal notice and Privacy policy

Done and repushed.

**Comment by oliverklee** [comment]
Just had a call with @alexander-nitsche. This is our conclusion:

- Yes, we should do this with variables.
- The variable to have this CoC link should always be set when rendering for docs.typo3.org, and authors should not be able to override this.
- For rendering outside of docs.typo3.org, authors can set the variable (or remove it) any way they like.

@alexander-nitsche I hope I got everything right. Please let me know if anything is not correct. Thanks!

**Comment by alexander-nitsche** [comment]
@oliverklee : yes, correct
@marble : would be great to align the rendering process and template variables with existing links in footer:
1. Upper links "Home", "Repository", "Issues", "Contact" and "Discussions" are displayed only if set in the template variables `project_*`.
2. Lower links "Legal Notice", "Privacy Policy" and "Code of Conduct" are displayed only if set in the template variables `<tbd>_*` **but** the rendering process is setting (and overwriting) them explicitly when rendering for docs.typo3.org context.

**Comment by marble** [comment]
I'll transfer the following to a new ticket

>>>>>>>>>>>>from above>>>>>>>>>>><<<<
> @marble : Would be great to align the rendering process and template variables with existing links in footer:

    Upper links "Home", "Repository", "Issues", "Contact" and "Discussions" are displayed only if set in the template variables project_*.
    Lower links "Legal Notice", "Privacy Policy" and "Code of Conduct" are displayed only if set in the template variables <tbd>_* but the rendering process is setting (and overwriting) them explicitly when rendering for docs.typo3.org context.
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

**Comment by oliverklee** [comment]
Thanks, @marble!

**Pull request merged**
